---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
cluster.name: docker-cluster
network.host: 0.0.0.0


# 로컬 테스트에서 http로 인한 반복적 충돌 로그 방지
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: false
xpack.security.transport.ssl:
  enabled: false
