#------------------------------------------------------------------
# Common variable
#------------------------------------------------------------------
x-variables:  
  password: &password "sv_demo"
  ELASTIC_VERSION: &elastic_version 8.17.2

#------------------------------------------------------------------
# Volumes
#------------------------------------------------------------------
volumes:
  elasticsearch:
    driver: local

services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 5580:8080  
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    volumes:
      - /home/catch/bench-sv/SV_ETL_DEMO/kui/config.yml:/etc/kafkaui/dynamic_config.yml
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka_net

#------------------------------------------------------------------
# Kafka Zookeeper
#------------------------------------------------------------------
  zookeeper-1:
    hostname: zookeeper-1
    image: confluentinc/cp-zookeeper:latest
    container_name: sv-zookeeper-1
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
      ZOOKEEPER_DATA_DIR: /zookeeper/data
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    ports:
      - "12181:2181"
      - "12888:2888"
      - "13888:3888"
    volumes:
      - ./zookeeper/data/1:/zookeeper/data
    networks:
      - kafka_net

  zookeeper-2:
    hostname: zookeeper-2
    image: confluentinc/cp-zookeeper:latest
    container_name: sv-zookeeper-2
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
      ZOOKEEPER_DATA_DIR: /zookeeper/data
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    ports:
      - "22181:2181"
      - "22888:2888"
      - "23888:3888"
    volumes:
      - ./zookeeper/data/2:/zookeeper/data
    networks:
      - kafka_net

  zookeeper-3:
    hostname: zookeeper-3
    image: confluentinc/cp-zookeeper:latest
    container_name: sv-zookeeper-3
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
      ZOOKEEPER_DATA_DIR: /zookeeper/data
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    ports:
      - "32181:2181"
      - "32888:2888"
      - "33888:3888"
    volumes:
      - ./zookeeper/data/3:/zookeeper/data
    networks:
      - kafka_net

#------------------------------------------------------------------
# Kafka Broker
#------------------------------------------------------------------
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    container_name: sv-kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xmx4G -Xms1G -XX:+UseG1GC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_LOG_DIR: /kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "19092:9092"
    volumes:
      - ./kafka/logs/1:/kafka
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka_net

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: sv-kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_HEAP_OPTS: -Xmx4G -Xms1G -XX:+UseG1GC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "29092:9092"
    volumes:
      - ./kafka/logs/2:/kafka
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka_net

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: sv-kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_HEAP_OPTS: -Xmx4G -Xms1G -XX:+UseG1GC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "39092:9092"
    volumes:
      - ./kafka/logs/3:/kafka
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka_net

#------------------------------------------------------------------
# Kafka Manager
#------------------------------------------------------------------
  akhq:
    image: tchiotludo/akhq:latest
    hostname: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: kafka-1:19092,kafka-2:29092,kafka-3:39092
    ports:
      - 5680:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka_net

#------------------------------------------------------------------
# ELK
# https://github.com/deviantony/docker-elk
#------------------------------------------------------------------
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: *elastic_version
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: *password # 편의상 하드코딩. (본래 setup 스크립트 호출 방식)
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    restart: unless-stopped
    networks:
      - kafka_net

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: *elastic_version
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: *password # ${LOGSTASH_INTERNAL_PASSWORD:-}
    depends_on:
      - elasticsearch
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka_net

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: *elastic_version
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: *password # ${KIBANA_SYSTEM_PASSWORD:-}
    depends_on:
      - elasticsearch
    networks:
      - kafka_net


#------------------------------------------------------------------
# Network
#------------------------------------------------------------------
networks:
  kafka_net:
    driver: bridge
